---
- name: "Deploy TWO Identical Windows VMs"
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    azure_tenant_id: "87742002-ea9f-4d0c-a979-6c0dd90a4a18"
    azure_subscription_id: "3961ff7d-1efb-4020-ba80-0ecb29884f8e"

    marketplace_image: "MicrosoftWindowsServer:WindowsServer:2019-Datacenter-gensecond:latest"

    random_id: "600"
    azure_location: "northeurope"
    target_resource_group: "rg-openbas-win-{{ random_id }}"


    vm_names:
      - "BASVM1"
      - "BASVM2"

    vm_size: "Standard_DC2s_v3"

    # Creation Admin
    admin_username: "openbasadmin"
    temp_admin_password: "FontysBas123!"

    # NETWORK NAMES
    vnet_name: "winVnet"
    subnet_name: "winSubnet"
    nsg_name: "winNSG"

  tasks:
    - name: Create resource group
      command: >
        az group create
        --subscription {{ azure_subscription_id }}
        --name {{ target_resource_group }}
        --location {{ azure_location }}

    - name: Create VNet
      command: >
        az network vnet create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name {{ vnet_name }}
        --address-prefix 10.0.0.0/16
            - name: Create subnet
      command: >
        az network vnet subnet create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --vnet-name {{ vnet_name }}
        --name {{ subnet_name }}
        --address-prefix 10.0.1.0/24

    - name: Create NSG
      command: >
        az network nsg create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name {{ nsg_name }}

    - name: Allow RDP (3389)
      command: >
        az network nsg rule create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --nsg-name {{ nsg_name }}
        --name AllowRDP
        --priority 1000
        --destination-port-ranges 3389
        --protocol Tcp
        --access Allow
        --direction Inbound

    - name: Allow SMB (445)
      command: >
        az network nsg rule create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --nsg-name {{ nsg_name }}
        --name AllowSMB
        --priority 1010
        --destination-port-ranges 445
        --protocol Tcp
        --access Allow
        --direction Inbound
    - name: Create Public IPs
      command: >
        az network public-ip create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name {{ item }}-PublicIP
        --allocation-method Static
      loop: "{{ vm_names }}"

    - name: Create NICs
      command: >
        az network nic create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name {{ item }}-NIC
        --vnet-name {{ vnet_name }}
        --subnet {{ subnet_name }}
        --public-ip-address {{ item }}-PublicIP
        --network-security-group {{ nsg_name }}
      loop: "{{ vm_names }}"

    - name: Create Windows VMs (Gen 2)
      command: >
        az vm create
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name {{ item }}
        --nics {{ item }}-NIC
        --image {{ marketplace_image }}
        --admin-username {{ admin_username }}
        --admin-password {{ temp_admin_password }}
        --size {{ vm_size }}
      loop: "{{ vm_names }}"

    - name: "Post-Config: Create Admin2 & Open Firewall"
      command: >
        az vm run-command invoke
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name {{ item }}
        --command-id RunPowerShellScript
        --scripts "net user Admin2 \"Passw0rd!\" /add; net localgroup Administrators Admin2 /add; netsh advfirewall firewall set rule group='File and Printer Sharing' new enable=yes"
      loop: "{{ vm_names }}"
      # --- DISPLAY OUTPUT ---

    - name: Show Public IP for BASVM1
      command: >
        az vm list-ip-addresses
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name BASVM1
        --query "[0].virtualMachine.network.publicIpAddresses[0].ipAddress"
        --output tsv
      register: ip_vm1

    - name: Show Public IP for BASVM2
      command: >
        az vm list-ip-addresses
        --subscription {{ azure_subscription_id }}
        --resource-group {{ target_resource_group }}
        --name BASVM2
        --query "[0].virtualMachine.network.publicIpAddresses[0].ipAddress"
        --output tsv
      register: ip_vm2

    - debug:
        msg:
          - "---------------------------------------------"
          - "VM 1: BASVM1 | IP: {{ ip_vm1.stdout }} | User: Admin2 | Pass: Passw0rd!"
          - "VM 2: BASVM2 | IP: {{ ip_vm2.stdout }} | User: Admin2 | Pass: Passw0rd!"
          - "---------------------------------------------"
